"""Add diet adherence and notes

Revision ID: 0ea9d917e388
Revises: 5088b067b034
Create Date: 2026-06-09 19:33:49.385474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ea9d917e388'
down_revision: Union[str, None] = '5088b067b034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('diet_adherence', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dailylog', sa.Column('diet_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailylog', 'diet_notes')
    op.drop_column('dailylog', 'diet_adherence')
    # ### end Alembic commands ###
