"""Add nutrition models FoodCategory and FoodItem

Revision ID: 1e017e7cc328
Revises: 7434728a92ef
Create Date: 2026-05-31 00:30:44.240573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1e017e7cc328'
down_revision: Union[str, None] = '7434728a92ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodcategory',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_foodcategory_code'), 'foodcategory', ['code'], unique=False)
    op.create_table('fooditem',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('base_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_serving_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_serving_weight', sa.Float(), nullable=True),
    sa.Column('is_system_data', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_code'], ['foodcategory.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fooditem_name'), 'fooditem', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fooditem_name'), table_name='fooditem')
    op.drop_table('fooditem')
    op.drop_index(op.f('ix_foodcategory_code'), table_name='foodcategory')
    op.drop_table('foodcategory')
    # ### end Alembic commands ###
