"""Add is_template and assigned_by_coach_id

Revision ID: 2e974363a0e3
Revises: 9d59f8ed8b65
Create Date: 2026-06-28 14:02:22.626355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e974363a0e3'
down_revision: Union[str, None] = '9d59f8ed8b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('assigned_by_coach_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'user', ['assigned_by_coach_id'], ['id'])
    op.add_column('workoutprogram', sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    op.add_column('workoutprogram', sa.Column('assigned_by_coach_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workoutprogram_is_template'), 'workoutprogram', ['is_template'], unique=False)
    op.create_foreign_key(None, 'workoutprogram', 'user', ['assigned_by_coach_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workoutprogram', type_='foreignkey')
    op.drop_index(op.f('ix_workoutprogram_is_template'), table_name='workoutprogram')
    op.drop_column('workoutprogram', 'assigned_by_coach_id')
    op.drop_column('workoutprogram', 'is_template')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'assigned_by_coach_id')
    # ### end Alembic commands ###
