"""Add cardio and steps to DailyLog

Revision ID: 5088b067b034
Revises: 98ef83a487ad
Create Date: 2026-06-09 19:14:35.317281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5088b067b034'
down_revision: Union[str, None] = '98ef83a487ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('cardio_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('cardio_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailylog', 'cardio_type')
    op.drop_column('dailylog', 'cardio_duration_minutes')
    op.drop_column('dailylog', 'steps')
    # ### end Alembic commands ###
