"""add_client_table_and_session_client_id

Revision ID: 602cd111fddf
Revises: 2e974363a0e3
Create Date: 2026-06-28 16:58:30.934901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '602cd111fddf'
down_revision: Union[str, None] = '2e974363a0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('fitness_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_level', sa.Float(), nullable=True),
    sa.Column('training_frequency', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_client_coach_id'), 'client', ['coach_id'], unique=False)
    op.create_index(op.f('ix_client_phone'), 'client', ['phone'], unique=False)
    op.create_index(op.f('ix_client_status'), 'client', ['status'], unique=False)
    op.add_column('session', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_session_client_id'), 'session', ['client_id'], unique=False)
    op.create_foreign_key(None, 'session', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_index(op.f('ix_session_client_id'), table_name='session')
    op.drop_column('session', 'client_id')
    op.drop_index(op.f('ix_client_status'), table_name='client')
    op.drop_index(op.f('ix_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_coach_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
