"""Add base fields to all models

Revision ID: 6791d8b723d3
Revises: 0734ecdd68c7
Create Date: 2026-05-29 23:09:59.455429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6791d8b723d3'
down_revision: Union[str, None] = '0734ecdd68c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('dailylog', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('dailylog', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('permission', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('permission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('permission', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('permission', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('phase', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('phase', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('phase', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('phase', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('phase', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('role', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('role', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('role', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('session', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('session', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'created_by')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('session', 'is_active')
    op.drop_column('session', 'updated_by')
    op.drop_column('session', 'created_by')
    op.drop_column('session', 'updated_at')
    op.drop_column('session', 'created_at')
    op.drop_column('role', 'is_active')
    op.drop_column('role', 'updated_by')
    op.drop_column('role', 'created_by')
    op.drop_column('role', 'updated_at')
    op.drop_column('role', 'created_at')
    op.drop_column('phase', 'is_active')
    op.drop_column('phase', 'updated_by')
    op.drop_column('phase', 'created_by')
    op.drop_column('phase', 'updated_at')
    op.drop_column('phase', 'created_at')
    op.drop_column('permission', 'is_active')
    op.drop_column('permission', 'updated_by')
    op.drop_column('permission', 'created_by')
    op.drop_column('permission', 'updated_at')
    op.drop_column('permission', 'created_at')
    op.drop_column('dailylog', 'is_active')
    op.drop_column('dailylog', 'updated_by')
    op.drop_column('dailylog', 'created_by')
    op.drop_column('dailylog', 'updated_at')
    op.drop_column('dailylog', 'created_at')
    # ### end Alembic commands ###
