"""Add chest waist hips to DailyLog

Revision ID: 7210b178a508
Revises: 8d64667e9021
Create Date: 2026-06-03 23:21:59.036356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7210b178a508'
down_revision: Union[str, None] = '8d64667e9021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('chest_measure', sa.Float(), nullable=True))
    op.add_column('dailylog', sa.Column('waist_measure', sa.Float(), nullable=True))
    op.add_column('dailylog', sa.Column('hips_measure', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailylog', 'hips_measure')
    op.drop_column('dailylog', 'waist_measure')
    op.drop_column('dailylog', 'chest_measure')
    # ### end Alembic commands ###
