"""Add profile fields to User

Revision ID: 7434728a92ef
Revises: 6791d8b723d3
Create Date: 2026-05-30 23:57:28.767669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7434728a92ef'
down_revision: Union[str, None] = '6791d8b723d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('current_weight', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('training_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'training_frequency')
    op.drop_column('user', 'height')
    op.drop_column('user', 'current_weight')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
