"""Add workout_program_snapshot

Revision ID: 81e2e9170e92
Revises: b04e2dbe0050
Create Date: 2026-06-03 19:22:12.908336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81e2e9170e92'
down_revision: Union[str, None] = 'b04e2dbe0050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('workout_program_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phase', 'workout_program_snapshot')
    # ### end Alembic commands ###
