"""add_user_profile_fields_for_nutrition

Revision ID: 8d64667e9021
Revises: 81e2e9170e92
Create Date: 2026-06-03 19:56:47.922823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d64667e9021'
down_revision: Union[str, None] = '81e2e9170e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('body_fat_percentage', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('activity_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity_level')
    op.drop_column('user', 'body_fat_percentage')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
