"""Add diet_completed_meal_ids to DailyLog

Revision ID: 9d59f8ed8b65
Revises: a42f4560af26
Create Date: 2026-06-11 22:49:29.143874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d59f8ed8b65'
down_revision: Union[str, None] = 'a42f4560af26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('diet_completed_meal_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailylog', 'diet_completed_meal_ids')
    # ### end Alembic commands ###
