"""Update nutrition tracking to meal based

Revision ID: a42f4560af26
Revises: 0ea9d917e388
Create Date: 2026-06-09 19:48:43.303088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a42f4560af26'
down_revision: Union[str, None] = '0ea9d917e388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('diet_meals_completed', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('diet_target_meals', sa.Integer(), nullable=True))
    op.add_column('dailylog', sa.Column('diet_protein_estimated', sa.Boolean(), nullable=True))
    op.add_column('dailylog', sa.Column('diet_cheat_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('dailylog', 'diet_adherence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailylog', sa.Column('diet_adherence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('dailylog', 'diet_cheat_status')
    op.drop_column('dailylog', 'diet_protein_estimated')
    op.drop_column('dailylog', 'diet_target_meals')
    op.drop_column('dailylog', 'diet_meals_completed')
    # ### end Alembic commands ###
