"""update_phase_schema

Revision ID: b04e2dbe0050
Revises: 46fc111c67f3
Create Date: 2026-06-02 22:50:30.658250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b04e2dbe0050'
down_revision: Union[str, None] = '46fc111c67f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('phase', 'nutrition_score_weight')
    op.drop_column('phase', 'weight_score_weight')
    op.drop_column('phase', 'workout_score_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phase', sa.Column('workout_score_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.3'::double precision"), autoincrement=False, nullable=False))
    op.add_column('phase', sa.Column('weight_score_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.2'::double precision"), autoincrement=False, nullable=False))
    op.add_column('phase', sa.Column('nutrition_score_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('phase', 'description')
    # ### end Alembic commands ###
