"""Add image_url to FoodItem

Revision ID: b4554ff35673
Revises: 1e017e7cc328
Create Date: 2026-05-31 21:41:29.316551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4554ff35673'
down_revision: Union[str, None] = '1e017e7cc328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fooditem', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fooditem', 'image_url')
    # ### end Alembic commands ###
